name: Validate Sharp Data

on: 
  push:
    paths:
      - 'Sharp/Data/**'
      - .github/workflows/validate-sharp-data.yml

jobs:
  validate:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Validate Data
      uses: 7474/SRC-DataLinter@master
      with:
        files: 'Sharp/Data/'
