name: Validate Sharp Data

on: 
  push:
    paths:
      - 'Sharp/Data/**'
      - .github/workflows/validate-sharp-data.yml

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Validate Data
      uses: 7474/SRC-DataLinter@master
      with:
        files: 'Sharp/Data/'
